"""Initial governed registry, execution metadata, and business audit schema.

Revision ID: 0001_governed_workflow_api
Revises: None
"""

import sqlalchemy as sa
from alembic import op

revision = "0001_governed_workflow_api"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_definitions",
        sa.Column("registry_id", sa.String(length=36), nullable=False),
        sa.Column("definition_id", sa.String(length=256), nullable=False),
        sa.Column("workflow_type", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("definition_document", sa.JSON(), nullable=False),
        sa.Column("owner", sa.String(length=256), nullable=False),
        sa.Column("dependencies", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=256), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.String(length=256), nullable=True),
        sa.Column("promoted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("promoted_by", sa.String(length=256), nullable=True),
        sa.Column("tenant", sa.String(length=128), nullable=False),
        sa.Column("business_domain", sa.String(length=128), nullable=False),
        sa.Column("application", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("registry_id"),
        sa.UniqueConstraint(
            "tenant",
            "business_domain",
            "application",
            "workflow_type",
            "version",
            name="uq_definition_revision",
        ),
    )
    op.create_index(
        "ix_definition_scope",
        "workflow_definitions",
        ["tenant", "business_domain", "application", "created_at"],
        unique=False,
    )
    op.create_table(
        "workflow_executions",
        sa.Column("workflow_id", sa.String(length=256), nullable=False),
        sa.Column("run_id", sa.String(length=256), nullable=True),
        sa.Column("workflow_type", sa.String(length=128), nullable=False),
        sa.Column("definition_id", sa.String(length=256), nullable=False),
        sa.Column("definition_version", sa.String(length=64), nullable=False),
        sa.Column("definition_document", sa.JSON(), nullable=False),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("variables", sa.JSON(), nullable=False),
        sa.Column("business_reference", sa.String(length=256), nullable=False),
        sa.Column("correlation_id", sa.String(length=256), nullable=False),
        sa.Column("idempotency_key", sa.String(length=256), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=256), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("current_step", sa.String(length=256), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=256), nullable=True),
        sa.Column("failure_summary", sa.Text(), nullable=True),
        sa.Column("tenant", sa.String(length=128), nullable=False),
        sa.Column("business_domain", sa.String(length=128), nullable=False),
        sa.Column("application", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("workflow_id"),
        sa.UniqueConstraint(
            "tenant",
            "business_domain",
            "application",
            "workflow_type",
            "idempotency_key",
            name="uq_execution_idempotency",
        ),
    )
    op.create_index(
        "ix_execution_scope",
        "workflow_executions",
        ["tenant", "business_domain", "application", "started_at"],
        unique=False,
    )
    op.create_table(
        "workflow_audit_events",
        sa.Column("ordinal", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("workflow_id", sa.String(length=256), nullable=True),
        sa.Column("projection_key", sa.String(length=128), nullable=True),
        sa.Column("run_id", sa.String(length=256), nullable=True),
        sa.Column("workflow_type", sa.String(length=128), nullable=True),
        sa.Column("definition_version", sa.String(length=64), nullable=True),
        sa.Column("business_reference", sa.String(length=256), nullable=True),
        sa.Column("step", sa.String(length=256), nullable=True),
        sa.Column("previous_state", sa.String(length=32), nullable=True),
        sa.Column("new_state", sa.String(length=32), nullable=True),
        sa.Column("actor", sa.String(length=256), nullable=False),
        sa.Column("correlation_id", sa.String(length=256), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("retention_class", sa.String(length=64), nullable=False),
        sa.Column("tenant", sa.String(length=128), nullable=False),
        sa.Column("business_domain", sa.String(length=128), nullable=False),
        sa.Column("application", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow_executions.workflow_id"],
        ),
        sa.PrimaryKeyConstraint("ordinal"),
        sa.UniqueConstraint("event_id"),
        sa.UniqueConstraint("workflow_id", "projection_key", name="uq_audit_projection"),
    )
    op.create_index(
        "ix_audit_scope_workflow",
        "workflow_audit_events",
        ["tenant", "business_domain", "application", "workflow_id"],
        unique=False,
    )
    op.create_table(
        "workflow_promotions",
        sa.Column("promotion_id", sa.String(length=36), nullable=False),
        sa.Column("workflow_type", sa.String(length=128), nullable=False),
        sa.Column("environment", sa.String(length=128), nullable=False),
        sa.Column("registry_id", sa.String(length=36), nullable=False),
        sa.Column("promoted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("promoted_by", sa.String(length=256), nullable=False),
        sa.Column("tenant", sa.String(length=128), nullable=False),
        sa.Column("business_domain", sa.String(length=128), nullable=False),
        sa.Column("application", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["registry_id"],
            ["workflow_definitions.registry_id"],
        ),
        sa.PrimaryKeyConstraint("promotion_id"),
        sa.UniqueConstraint(
            "tenant",
            "business_domain",
            "application",
            "workflow_type",
            "environment",
            name="uq_promotion_slot",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workflow_promotions")
    op.drop_index("ix_audit_scope_workflow", table_name="workflow_audit_events")
    op.drop_table("workflow_audit_events")
    op.drop_index("ix_execution_scope", table_name="workflow_executions")
    op.drop_table("workflow_executions")
    op.drop_index("ix_definition_scope", table_name="workflow_definitions")
    op.drop_table("workflow_definitions")
    # ### end Alembic commands ###
